language: node_js
node_js:
  - '10.18.0'
  - '11.15.0'
  - '12.14.0'
  - '13.14.0'
  - '14.0.0'
  - '14.9.0'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install
script:
  - "npm run lint"
  - "npm run build"
after_success:
  - npm run coverage
