language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install
script:
  - "npm run lint"
  - "npm run build"
